@HOST = https://cfd-reactjs.herokuapp.com/
@ACEESSTOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhbmd0aHV5ZW52dW9uZ0BnbWFpbC5jb20iLCJfaWQiOiI1ZmNmM2M1NTI1Mjk0MTI4NTAzOGUwOWMiLCJpYXQiOjE2MDc0OTczODksImV4cCI6MTYwNzQ5NzQwNH0.SeXjiBeC_JR3pskFYQ2NreR9E08WZcXfqviOI-IkeME

GET {{HOST}}rest/elearning_course
Authorization: {{ACEESSTOKEN}}

###

POST {{HOST}}api/login
Content-Type: application/json

{   
    "email":"dangthuyenvuong@gmail.com",
    "password":"123456789"
}

###

POST  {{HOST}}api/refresh-token
Content-Type: application/json

{
    "refreshToken" :"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhbmd0aHV5ZW52dW9uZ0BnbWFpbC5jb20iLCJfaWQiOiI1ZmNmM2M1NTI1Mjk0MTI4NTAzOGUwOWMiLCJpYXQiOjE2MDc0OTc3MzN9.N6fTeEBwNxBi2DgPd3bAFzSX9tLcezkzChgP6RHRBCY"
    
}